language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.6'
  - '7.1'
  - '7.2'

install: composer update

script:
  - ./vendor/bin/phpcs . --standard=phpcs.ruleset.xml
  - ./vendor/bin/phpunit
  
before_deploy:
- rm -rf vendor
- rm -rf .git
- composer install --no-dev
- rm composer.lock
- rm -rf vendor/**/**/bin && rm -rf vendor/bin && rm -rf vendor/**/**/Tests
- zip -r wp-gatsby-markdown-exporter.zip .

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file: wp-gatsby-markdown-exporter.zip
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      php: '7.2'
